version: "3"

services:
  webserver:
    build:
      context: ./bin/${WEBSERVER}
    container_name: "${WEBSERVER}"
    restart: "on-failure"
    ports:
      - "${WEBSERVER_PORT}:80"
      - "${WEBSERVER_PORT_SSL}:443"
    links:
      - mysql_inout
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
  mysql_inout:
    build:
      context: "./bin/${DATABASE}"
    container_name: "mysql_inout"
    restart: "on-failure"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin_inout"
    restart: "on-failure"
    links:
      - mysql_inout
    environment:
      PMA_HOST: mysql_inout
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - /sessions
      - ${PHPMYADMIN_PHP_INI}:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini